service: my-express-application

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-central-1

functions:
  test:
    handler: index.test
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
      - method: get
      - cors: true

include:
  - dist/**
  - node_modules/**