service: my-express-application
plugins:
  - serverless-finch
  - serverless-offline
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-central-1

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
custom:
  client:
   bucketName: bodychange-test-public-20180521
   distributionFolder: templates/
